title: scratch-physcomp1
hero_image: images/banner.png
description: scratch-physcomp1 description
version: 4
listed: false
copyedit: true
last_tested: "2021-02-25"
steps:
  - title: Introduction
  - title: Test your Circuit
  - title: Code your Circuit
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: What next?
